version: '3.8'

services:
  vocabx-api:
    container_name: vocabx-api
    build:
      context: ./vocabx-api
      dockerfile: Dockerfile
      args:
        user: vicky
        uid: 1000
    restart: always
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - vendor_data:/var/www/vendor
    ports:
      - "9000:9000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true

  vocabx-web:
    container_name: vocabx-web
    build:
      context: ./vocabx-web
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:8080
    ports:
      - "3000:80"
    depends_on:
      - vocabx-api

  webserver:
    container_name: laravel_webserver
    image: nginx:alpine
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx/my-nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - vocabx-web

  db:
    container_name: vocabx-db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - ./npm_data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - vocabx-api
      - vocabx-web

volumes:
  dbdata:
  vendor_data:
  npm_data:
  letsencrypt: